core = "6.x"
api = "2"
projects[drupal][type] = "core"
projects[openatrium][type] = "profile"
projects[openatrium][download][type] = "git"
projects[openatrium][download][url] = "git://git.drupal.org/project/openatrium.git"
projects[openatrium][download][tag] = "6.x-1.6"
